# Problem 2: Even Fibonacci Numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four  
# million, find the sum of the even-valued terms.

a = 1
b = 2
fibo = [a, b]

while b < 3000000:
	a, b = b, a+b
	fibo.append(b)
	print fibo
 
evens = [num for num in fibo if num % 2 == 0]
print sum(evens)

